language: php
php:
  - "7.3"
before_script:
  - npm install -g bower
  - bower install
script: phpunit tests

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "rZc87bjaySMUJ5yqZgrTfgxRW1+cpg4iLWsVoIiXZwNtPOa8sK105oS+q6W6c1Cik4NrFQHIEULOVGVwt8/NDWJApDZFkNJ4VapqDEgYlaNEWn6J3N4uMASmHV33aThHaoGGZSAIuZHQZijIqg4cYFZ5bk0nRP8Ta5mtkHgMYpFRJmxZRGzqkf0XLdyttZpRBKa64p6QQXZ4TuiOc/g1oRPzJ/23p9fD0qmPiPpFARMjdAgR/4flKvzup36Gj5M4fA11bMpHrupSNvdbvIntbVytGWs2Uf2MrufMwSbeiA01qf2kg29st27tKv0SKuWEu+I/33gG5TGcP1Uan9h32QzklzdKaDQk5hwh+PrWSi2SZ93bNWLIkHxDiaV7aF0oDu1Bf7RqzLQQ0ofX++zlroiFqxH8ELcgu+YfPqbAXEIZDNJXEyKV0PEJ/6icHnPgkbiZrk2Zufl9pxl3Nqfbd4Np9T4E3ABzoeFbjp8kquhn8n1QRJvUvMF+H7mln5yDuMiwyERuMwRirAv0JSqCf3T60DvTTYWciUzfvdjNP8pNy1JCrmN3EuzJbI7f+K00pbc1IWzUjfZQdy5rCoeN9/SOTg0jPj5J0R51rbcJmRWzOdjUzOTbDHh21fUOqWUZqDYpyy/EUIUQ4qIgKE2FJt7j8YsM/O27wxwVTFkPxUU="
  secret_access_key:
    secure: "roDa5i8Fl5tewnANoecj8GUie/TadpMlyZeGZenPxUoPldrLWvCh67I2zEPPnvIrNsjz9ms++1xyN1cL87pDnkrBPNobt9YCzzZrU8o0HxVnHREPGLpofCQjg7Q5C5sURq/FUgmH1oB4doWf0uYxR/FRpt9iMspKnpZQP/3nHwPrh1PVVkwaj1wIn8Gc07ZXim+PIDRNruphqkGvrnhpBgadOa35ECWnZGEGeua3NWYDw8dIVOEjxij6J94UmSqaC/UWqaj9mIkkEGWhPS3B9tf9e7+MSsaG7RYiYdHMNfWeSOhzdcUAjmsjG63Raj1ssScjLQCTsFvWATETFcLtuu5aLQ0KEd47bzz38ontweLJssMCv8uK/bcwLUGZJjtK6v8LLGKO2IKRjD3BZdgn0KgVNjGUDREUt+QtAVbpxamM+8g37STaLpgOb7rnrH0qyh3qre6nCDPxxz5qaYopTE4ZdwCBGaYqErH1GHRV+RuPG2YgFBIrBx2lVrGUXBBA4Q2Eip44Nj5ChMiw9Lt7yBofvgQKm7CxBXowk6goxWdHUfYdFbFo9piuyatnVg/DuAshqjp8Du0GXNMur7n1MIeHOnZKYowC2VHxyTmdLX7k8QyvN/SJEQvl0I+CVKhviv4Ll89U5EdhbuW5RP3CzT7LkumZdUE9Q+tuGB0eCJI="
  region: "eu-central-1"
  app: "Planning-Poker"
  env: "planning-poker"
  bucket_name: "elasticbeanstalk-eu-central-1-168876705064"
