language: php
php:
  - 7.3

before_install:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
  - composer install --dev

before_script:
  - npm install -g bower
  - bower install

script:
  - ./vendor/bin/phpunit tests
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v