language: php
php:
  - 7.3

before_script:
  - composer install
  - npm install -g bower
  - bower install

script:
  - ./vendor/bin/phpunit tests

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESSKEYID"
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-central-1"
  app: "Planning-Poker"
  env: "planning-poker"
  bucket_name: "elasticbeanstalk-eu-central-1-168876705064"
  on:
    branch: master
