language: php
php:
  - 7.3

before_script:
  - composer install
  - npm install -g bower
  - bower install

script:
  - "./vendor/bin/phpunit tests"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: AWS_SECRET_ACCESS_KEY
  region: eu-central-1
  env: planning-poker
  bucket: elasticbeanstalk-eu-central-1-168876705064
  on:
    branch: master
  edge: true
