language: php
php:
  - "7.3"
before_script:
  - composer install
  - npm install -g bower
  - bower install
script:
  - ./vendor/bin/phpunit tests
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry ./vendor/bin/php-coveralls
  # or enable logging
  - travis_retry ./vendor/bin/php-coveralls -v
