language: php
php:
  - 7.3
  - 7.4

before_install:
  - composer install --dev

before_script:
  - npm install -g bower
  - bower install

script:
  - ./vendor/bin/phpunit tests
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v