        <div class="footer-clean">
            <footer>
                <div class="container">
                    <div class="row justify-content-center">
                         <div class="col-sm-4 col-md-3 item">
                            <h3>Services</h3>
                            <ul>
                                <li><a href="<?= $this->makeURL("services/webdesign"); ?>">Web design</a></li>
                                <li><a href="<?= $this->makeURL("services/development"); ?>">Entwicklung</a></li>
                                <li><a href="<?= $this->makeURL("services/hosting"); ?>">Hosting</a></li>
                            </ul>
                        </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Info</h3>
                        <ul>
                            <li><a href="<?= $this->makeURL("about/project"); ?>">Projekt</a></li>
                            <li><a href="<?= $this->makeURL("about/team"); ?>">Team</a></li>
                        </ul>
                    </div>
                        <div class="col-lg-3 item social">
                            <a href="https://github.com/Drinkler/Planning-Poker" target="_blank">
                                <i class="icon ion-social-github"></i>
                            </a>
                            <a href="#">
                                <i class="icon ion-android-mail"></i>
                            </a>
                            <p class="copyright">Florian Drinkler, Luca Stanger © 2020</p>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <?= $this->getJS(); ?>
        <script>
            // Used to hide info bar after three seconds
            $(".alert").delay(3500).slideUp(200, function() {
                $(this).alert('close');
            });
        </script>
        <script src="<?= $this->makeURL('assets\js\ajaxfunctions.js') ?>"></script>
        </body>
</html>
