<?php

use PlanningPoker\Library\Config;
use PlanningPoker\Library\Flash;

?>
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
        <title>DHBW Poker</title>
        <link rel="shortcut icon" type="image/x-icon" href="<?= $this->makeURL("assets/img/planning_icon.png") ?>">
        <?= $this->getCSS(); ?>
        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    </head>
    <body>
        <div id="content">
        <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form method="post" action="<?= $this->makeURL("user/login")?>">
                    <div class="modal-body">
                        <h2 class="sr-only">Login Form</h2>
                        <div class="form-group">
                            <input class="form-control" type="email" name="email" placeholder="Email"/>
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="password" name="password" placeholder="Password"/>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Log In</button>
                    </div>
                </form>
            </div>
        </div>
        </div>
        <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="signupModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="signupModalLabel">Create an account</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form method="post" action="<?= $this->makeURL("user/create");?>">
                        <div class="modal-body">
                            <h2 class="sr-only">SignUp Form</h2>
                            <div class="form-group">
                                <input class="form-control" type="text" name="name" placeholder="Surname" minlength="2" maxlength="50"/>
                            </div>
                            <div class="form-group">
                                <input class="form-control" type="text" name="surname" placeholder="Name" minlength="2" maxlength="50"/>
                            </div>
                            <div class="form-group">
                                <input class="form-control" type="email" name="email" placeholder="Email" maxlength="100"/>
                            </div>
                            <div class="form-group">
                                <input class="form-control" type="password" name="password" placeholder="Password" minlength="8"/>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                        <div class="form-group">
                            <div class="g-recaptcha" data-sitekey="6LcbPuYUAAAAABSvTUYDZHeistTNRv0omkLpnMYK" data-callback="verifyRecaptchaCallback" data-expired-callback="expiredRecaptchaCallback"></div>
                            <input class="form-control d-none" data-recaptcha="true" data-error="Please complete the Captcha" />
                            <div class="help-block with-errors"></div>
                </div>
                </form>
            </div>
            </div>
        </div>
        <nav class="navbar navbar-light navbar-expand-md navigation-clean-button dropleft">
            <div class="container">
                <a class="navbar-brand" href="<?= $this->makeURL("index")?>">
                    <img src='<?= $this->makeURL("assets/img/planning_icon.png")?>' width="30px" height="30px" class="d-inline-block align-top" alt="">
                    DHBW Poker
                </a>
                <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                    <a class="nav-link" href="<?= $this->makeURL("lobby/sessions") ?>">Sessions</a>
                    </li>
                </ul>
            </div>
            <?= $this->getFile("_template/navigation") ?>
            </div>
        </nav>
            <div id="feedback" class="container">
                <?php if (($danger = Flash::danger())): ?>
                    <div class="alert alert-danger alert-dismissible fade show" role="alert"><strong><?= $this->escapeHTML($danger); ?></strong><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
                <?php
                endif;
                if (($info = Flash::info())):
                    ?>
                    <div class="alert alert-info alert-dismissible fade show" role="alert"><strong><?= $this->escapeHTML($info); ?></strong><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
                <?php
                endif;
                if (($success = Flash::success())):
                    ?>
                    <div class="alert alert-success alert-dismissible fade show" role="alert"><strong><?= $this->escapeHTML($success); ?></strong><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
                <?php
                endif;
                if (($warning = Flash::warning())):
                    ?>
                    <div class="alert alert-warning alert-dismissible fade show" role="alert"><strong><?= $this->escapeHTML($warning); ?></strong><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
                <?php
                endif;
                if (($errors = Flash::session(Config::get("SESSION_ERRORS")))):
                    ?>
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <h4>Errors:</h4>
                        <ul>
                            <?php foreach ($errors as $key => $values): ?>
                                <?php foreach ($values as $value): ?>
                                    <li><?= $this->escapeHTML($value); ?></li>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                <?php endif; ?>
            </div>
