<?php

use PlanningPoker\Library\Session;

?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card" style="margin-bottom: 30px;">
                <div class="card-body">
                    <div>
                        <p>This website was created as a project of the lecture "Web Engineering" of the fourth semester at the DHBW. This site is used to conduct a DHBW Poker session. The stories can be loaded as issues via URL of a github repository. The Scrum Master creates the lobby and gets an overview of all available stories as well as the joined participants. After the Scrum Master has set a Story active, the other participants can choose a card from a previously selected card set. Only the Scrum Master can see all selections. It is recommended to use an external communication software during the game.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card" style="margin-bottom: 30px;">
                <div class="card-body">
                    <h4 class="card-title">Create a session</h4>
                    <p class="card-text"> Give your session a name and choose the card set you want to play with. Share the ID with your team afterwards.</p>
                    <form action="<?= $this->makeURL("lobby/create")?>" method="POST">
                        <div class="form-group">
                            <label for="formLabelSelect">Session name:</label>
                            <input type="text" class="form-control" name="lobbyName" id="formLabelSelect" placeholder="My Session">
                        </div>
                        <div class="form-group">
                            <label for="formControlSelect">Cards:</label>
                            <select class="form-control" name="cards" id="formControlSelect">
                                <?php
                                $cardSets = [
                                    // 1, 3, 5, 8
                                    ['1', '2', '3', '5', '8'],
                                    // Standard fibonaci like series of values
                                    ['1', '2', '3', '5', '8', '13', '20', '40', '100'],
                                    // Special card set with '?' for unclear stories
                                    ['1', '2', '3', '5', '8', '13', '20', '40', '?'],
                                    // Powers of two used by other teams
                                    ['0', '1', '2', '4', '8', '16', '32', '64'],
                                    // Card set used to estimate hours as different fractions and multiples of a working day
                                    ['1', '2', '4', '8', '12', '16', '24', '32', '40'],
                                    // Demonstration of the coffee cup card
                                    ['&#9749;', '1', '2', '3', '5', '8', '13', '20', '?'],
                                    // T-shirt Size
                                    ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '?'],
                                    // Fibonacci number
                                    ['1', '2', '3', '5', '8', '13', '21', '34', '55', '89', '144', '&#9749;', '?'],
                                    // Fibonaci series including 0.5
                                    ['0.5', '1', '2', '3', '5', '8', '13', '20', '40', '100'],
                                    // Canadian Cash format
                                    ['1', '2', '5', '10', '20', '50', '100'],
                                    //Salesforce Estimates
                                    ['0.5', '1', '3', '5', '8']
                                ];

                                foreach ($cardSets as $key => $cardSet) {
                                    $key += 1;
                                    echo "<option value=$key>" . json_encode($cardSet) . "</option>";
                                }
                                ?>
                            </select>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-secondary">Create</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card" style="margin-bottom: 30px;">
                <div class="card-body">
                    <h4 class="card-title">Join a session</h4>
                    <p class="card-text"> You've got an issue ID? Submit it here to join a session</p>
                    <form action="<?= $this->makeURL("lobby/lobby") ?>" method="post">
                        <div class="form-group">
                            <label for="sessionID">Session-ID:</label>
                            <input type="text" class="form-control" name="lobbyid" id="sessionID" placeholder="z.B. 123456789">
                        </div>
                        <div class="form-group">
                            <label for="userName">Your name:</label>
                            <input type="text" class="form-control" id="userName" value="<?php echo (isset($_SESSION["user"]) && Session::get("user")->getUsername() ? Session::get("user")->getUsername() : 'Jon Doe')  ?>">
                        </div>
                        <br>
                        <button type="submit" name="action" value="Join" class="btn btn-secondary">Join</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>