<?php

use PlanningPoker\Library\Session;

?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card" style="margin-bottom: 30px;">
                <div class="card-body">
                    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card" style="margin-bottom: 30px;">
                <div class="card-body">
                    <h4 class="card-title">Erstelle eine Sitzung</h4>
                    <p class="card-text"> Gib deiner Sitzung einen Namen und wähle die Karte aus, welche du benutzen möchtest. Teile anschließend die erhaltene ID deinen Teilnehmern mit.</p>
                    <form action="<?= $this->makeURL("lobby/create")?>" method="POST">
                        <div class="form-group">
                            <label for="formLabelSelect">Sitzungs Name:</label>
                            <input type="text" class="form-control" name="lobbyName" id="formLabelSelect" placeholder="Meine Session">
                        </div>
                        <div class="form-group">
                            <label for="formControlSelect">Karten:</label>
                            <select class="form-control" name="cards" id="formControlSelect">
                                <?php
                                $cardSets = [
                                    // 1, 3, 5, 8
                                    ['1', '2', '3', '5', '8'],
                                    // Standard fibonaci like series of values
                                    ['1', '2', '3', '5', '8', '13', '20', '40', '100'],
                                    // Special card set with '?' for unclear stories
                                    ['1', '2', '3', '5', '8', '13', '20', '40', '?'],
                                    // Powers of two used by other teams
                                    ['0', '1', '2', '4', '8', '16', '32', '64'],
                                    // Card set used to estimate hours as different fractions and multiples of a working day
                                    ['1', '2', '4', '8', '12', '16', '24', '32', '40'],
                                    // Demonstration of the coffee cup card
                                    ['&#9749;', '1', '2', '3', '5', '8', '13', '20', '?'],
                                    // T-shirt Size
                                    ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '?'],
                                    // Fibonacci number
                                    ['1', '2', '3', '5', '8', '13', '21', '34', '55', '89', '144', '&#9749;', '?'],
                                    // Fibonaci series including 0.5
                                    ['0.5', '1', '2', '3', '5', '8', '13', '20', '40', '100'],
                                    // Canadian Cash format
                                    ['1', '2', '5', '10', '20', '50', '100'],
                                    // Standard fibonacci with shrug
                                    ['1', '2', '3', '5', '8', '13', '&#F937;'],
                                    //Salesforce Estimates
                                    ['0.5', '1', '3', '5', '8']
                                ];

                                foreach ($cardSets as $key => $cardSet) {
                                    $key += 1;
                                    echo "<option value=$key>" . json_encode($cardSet) . "</option>";
                                }
                                ?>
                            </select>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-secondary">Erstellen</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card" style="margin-bottom: 30px;">
                <div class="card-body">
                    <h4 class="card-title">Tritt einer Sitzung bei</h4>
                    <p class="card-text"> Du hast eine Sitzungs-ID? Gib sie hier ein um der Sitzung beizutreten</p>
                    <form action="<?= $this->makeURL("lobby/lobby") ?>" method="post">
                        <div class="form-group">
                            <label for="sessionID">Sitzungs-ID:</label>
                            <input type="text" class="form-control" name="lobbyid" id="sessionID" placeholder="z.B. 123456789">
                        </div>
                        <div class="form-group">
                            <label for="userName">Dein Name:</label>
                            <input type="text" class="form-control" id="userName" value="<?php echo (isset($_SESSION["user"]) && Session::get("user")->getUsername() ? Session::get("user")->getUsername() : 'Max Mustermann')  ?>">
                        </div>
                        <br>
                        <button type="submit" name="action" value="Join" class="btn btn-secondary">Beitreten</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                        Review bla
                </div>
            </div>
        </div>
    </div>
</div>