<?php use PlanningPoker\Library\Redirect;
use PlanningPoker\Library\Session;

// TODO: Define this in a config file
$cardSets = [
    // 1, 3, 5, 8
    ['1', '2', '3', '5', '8'],
    // Standard fibonaci like series of values
    ['1', '2', '3', '5', '8', '13', '20', '40', '100'],
    // Special card set with '?' for unclear stories
    ['1', '2', '3', '5', '8', '13', '20', '40', '?'],
    // Powers of two used by other teams
    ['0', '1', '2', '4', '8', '16', '32', '64'],
    // Card set used to estimate hours as different fractions and multiples of a working day
    ['1', '2', '4', '8', '12', '16', '24', '32', '40'],
    // Demonstration of the coffee cup card
    ['&#9749;', '1', '2', '3', '5', '8', '13', '20', '?'],
    // T-shirt Size
    ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '?'],
    // Fibonacci number
    ['1', '2', '3', '5', '8', '13', '21', '34', '55', '89', '144', '&#9749;', '?'],
    // Fibonaci series including 0.5
    ['0.5', '1', '2', '3', '5', '8', '13', '20', '40', '100'],
    // Canadian Cash format
    ['1', '2', '5', '10', '20', '50', '100'],
    // Standard fibonacci with shrug
    ['1', '2', '3', '5', '8', '13', '&#F937;'],
    //Salesforce Estimates
    ['0.5', '1', '3', '5', '8']
];


// External Tools
$externals = ["GitHub", "GitLab", "DevOps", "Jira"];

$idlobby = $this->vars[":idlobby"];
$iduser = $this->vars[":iduser"];
$idcreator = $this->vars[":idcreator"];
$idcards = $this->vars[":cards"] - 1;

$_SESSION["lobby"] = $idlobby;

?>


<?php if($iduser == $idcreator): ?>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <div class="card-body">
                        <h1> Masterview </h1>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <div class="card-body">
                        <h1 class="float-right"> LobbyID: <?= $idlobby ?></h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <table id="participants" class="table">
                        <thead>
                            <tr>
                                <th scope="col">Participant</th>
                                <th scope="col">Vote</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Luca</td>
                                <td>3</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <?php foreach($externals as $key=>$external): ?>
                            <a class="nav-item nav-link <?php if ($key == 0) { echo "active";} ?>" id="nav-<?= strtolower($external) ?>-tab" data-toggle="tab" href="#nav-<?= strtolower($external) ?>" role="tab" aria-controls="nav-<?= strtolower($external) ?>" aria-selected="true"><?= $external ?></a>
                        <?php endforeach; ?>
                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent" style="padding: 20px">
                        <?php foreach($externals as $key=>$external): ?>
                            <div class="tab-pane fade <?php if ($key == 0) { echo "show active";} ?>" id="nav-<?= strtolower($external) ?>" role="tabpanel" aria-labelledby="nav-<?= strtolower($external) ?>-tab">
                                <div class="form-group">
                                    <label for="exampleInputEmail1"><?= $external?> Repository Address</label>
                                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="https://github.com/Drinkler/Planning-Poker">
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card" style="margin-bottom: 30px;">
                    <div class="card-body">
                        <h4 class="card-title">Current Story:</h4>
                        <p class="card-text">Storydescription</p>
                    </div>
                </div>
            </div>
        </div>
        <form name="card-form" id="card-form" method="post" action="<?= $this->makeURL("lobby/lobby") ?>" style="display: compact;">
            <div class="row">
                <?php foreach ($cardSets[$idcards] as $key=>$card): ?>
                    <div class="col-md-6" style="padding: 0;" onclick="document.forms['card-form'].submit();">
                        <div class="card">
                            <div class="card-body" style="padding: 20px;">
                                <h6 class="display-1 text-center card-title"><?= $card ?></h6>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </form>
    </div>
<?php endif; ?>
