<?php

use PlanningPoker\Library\Flash;
use PlanningPoker\Library\Session;

if (empty(Session::get("user"))) {
    echo '<meta http-equiv="Refresh" content="0; url=' . $this->makeURL("lobby/sessions") . '" />';
    Flash::danger("You need to be logged in!");
} else {

// TODO: Define this in a config file
$cardSets = [
    // 1, 3, 5, 8
    ['1', '2', '3', '5', '8'],
    // Standard fibonaci like series of values
    ['1', '2', '3', '5', '8', '13', '20', '40', '100'],
    // Special card set with '?' for unclear stories
    ['1', '2', '3', '5', '8', '13', '20', '40', '?'],
    // Powers of two used by other teams
    ['0', '1', '2', '4', '8', '16', '32', '64'],
    // Card set used to estimate hours as different fractions and multiples of a working day
    ['1', '2', '4', '8', '12', '16', '24', '32', '40'],
    // Demonstration of the coffee cup card
    ['&#9749;', '1', '2', '3', '5', '8', '13', '20', '?'],
    // T-shirt Size
    ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '?'],
    // Fibonacci number
    ['1', '2', '3', '5', '8', '13', '21', '34', '55', '89', '144', '&#9749;', '?'],
    // Fibonaci series including 0.5
    ['0.5', '1', '2', '3', '5', '8', '13', '20', '40', '100'],
    // Canadian Cash format
    ['1', '2', '5', '10', '20', '50', '100'],
    // Standard fibonacci with shrug
    ['1', '2', '3', '5', '8', '13', '&#F937;'],
    //Salesforce Estimates
    ['0.5', '1', '3', '5', '8']
];


// External Tools
$externals = ["GitHub", "GitLab", "DevOps", "Jira"];

$idlobby = $this->vars[":idlobby"];
$iduser = $this->vars[":iduser"];
$idcreator = $this->vars[":idcreator"];
$idcards = $this->vars[":cards"] - 1;

$_SESSION["lobby"] = $idlobby;

foreach ($_POST as $postInput) {
    if ($postInput != "") {
        $url = $postInput;
    }
}

?>

<?php if($iduser == $idcreator): ?>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <div class="card-body">
                        <h1> Masterview </h1>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <div class="card-body">
                        <h1 class="float-md-none"> LobbyID: <?= $idlobby ?></h1>
                    </div>
                </div>
            </div>
        </div>
        <script>
        </script>
        <div class="row">
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Participant</th>
                                <th scope="col">Vote</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody id="participants"></tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card" style="margin-bottom: 30px;">
                    <input type="hidden" id="lobbyid" name="lobbyid" value="<?= $idlobby ?>">
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <?php foreach($externals as $key=>$external): ?>
                            <a class="nav-item nav-link <?php if ($key == 0) { echo "active";} ?>" id="nav-<?= strtolower($external) ?>-tab" data-toggle="tab" href="#nav-<?= strtolower($external) ?>" role="tab" aria-controls="nav-<?= strtolower($external) ?>" aria-selected="true"><?= $external ?></a>
                        <?php endforeach; ?>
                        </div>
                    </nav>
                    <div class="tab-content" id="nav-tabContent" style="padding: 20px">
                    <?php foreach($externals as $key=>$external): ?>
                        <div class="tab-pane fade <?php if ($key == 0) { echo "show active";} ?>" id="nav-<?= strtolower($external) ?>" role="tabpanel" aria-labelledby="nav-<?= strtolower($external) ?>-tab">
                            <div class="form-group">
                                <label for="<?= strtolower($external) ?>Input"><?= $external?> Repository Address</label>
                                <input type="url" class="form-control" name="<?= strtolower($external) ?>Input" id="<?= strtolower($external) ?>Input" aria-describedby="emailHelp" placeholder="https://github.com/Drinkler/Planning-Poker">
                            </div>
                        <div style="padding: 20px">
                            <button type="submit" class="btn btn-primary" onclick="fetchStoriesFrom<?= $external ?>()">Get stories from <?= $external ?></button>
                        </div>
                        </div>
                    <?php endforeach; ?>
                    </div>
                    <table id="stories" class="table"></table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h4 id="avg">Average score:</h4>
                        <br>
                        <h4 id="most">Most played card:</h4><a></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        window.setInterval(function () {
            getParticipants(<?= $idlobby ?>);
            getAvg(<?= $idlobby ?>);
            getMostPlayedCards(<?= $idlobby ?>);
        }, 1000);
    </script>

<?php else: ?>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card" style="margin-bottom: 30px;">
                    <div class="card-body">
                        <h4 class="card-title" id="title">Current Story:</h4>
                        <p class="card-text" id="description">Storydescription</p>
                    </div>
                </div>
            </div>
        </div>
            <div class="row">
                <?php foreach ($cardSets[$idcards] as $key=>$card): ?>
                    <!-- <form class="col-md-6" name="card-form" id="card-form<?= $key ?>" method="get" action="<?= $this->makeURL("ajax/vote") ?>"> -->
                    <div class="col-md-6">
                        <div class="card vote-tile pointer" style="padding: 0;">
                            <div class="card-body">
                                <h6 class="display-1 text-center card-title"><?= $card ?></h6>
                                <input type="hidden" name="voteid" value="<?= $key ?>">
                            </div>
                        </div>
                    </div>
                    <!-- </form> -->
                <?php endforeach; ?>
            </div>
    </div>
    <script>
        window.setInterval(function () {
            getCurrentActiveIssue(<?= $idlobby ?>);
        }, 1000);
    </script>
    <script>
        [].forEach.call(document.getElementsByClassName("vote-tile"), function (vt) {vt.addEventListener("click", function () {vote(this)})});
    </script>
<?php endif; }?>

