<div class="container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Host</th>
                    <th scope="col">Name</th>
                    <th scope="col">Created</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->vars as $key => $lobby): ?>
                    <tr>
                        <th scope="row"> <?= $key ?></th>
                        <td><?= $lobby["uname"] ?></td>
                        <td><?= $lobby["name"] ?></td>
                        <td><?= date("Y-m-d H:i:s", strtotime($lobby["created"]. ' UTC')) ?></td>
                        <td>
                            <div class="">
                                <form method="post" action="<?= $this->makeURL("lobby/lobby") ?>" style="display:inline;">
                                    <input type="hidden" name="lobbyid" value="<?= $lobby['lobbyid'] ?>">
                                    <button type="submit" name="action" value="Join" class="btn btn-outline-primary">Join</button>
                                    <?php if (!empty(\PlanningPoker\Library\Session::get("user"))): ?>
                                        <?php if ($lobby["creator"] == \PlanningPoker\Library\Session::get("user")->getId()): ?>
                                            <button type="submit" name="action" value="Delete" class="btn btn-outline-danger">Delete</button>
                                        <?php endif; ?>
                                    <?php endif;?>
                                </form>
                            </div>
                        </td>
                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>