<div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <img src="<?= $this->vars["avatar"] ?>" />
                <h3><?= $this->vars["user"]->getUsername() ?></h3>
            </div>
            <div class="col-md-5">
                <strong>Name:&nbsp;</strong><?= $this->vars["user"]->getName() ?><br>
                <strong>Surname:&nbsp;</strong><?= $this->vars["user"]->getSurname() ?><br>
                <strong>E-Mail:&nbsp;</strong><?= $this->vars["user"]->getEmail() ?><br>
                <p></p>
                <a href="<?= $this->makeURL("user/delete") ?>" class="dropdown-item text-danger"> Delete user</a>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</div>